# Generated by Django 4.1 on 2022-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuarto', models.IntegerField()),
                ('metro', models.IntegerField()),
                ('baño', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
